import { scrollLengthFromBeats } from "../story-timing";
import type { SceneConfig } from "./types";

const sceneBeatCounts = {
  chapter2Scene1: 4,
  chapter2Scene2: 5,
  chapter2Scene3: 4,
  chapter2Scene4: 4,
  chapter2Scene5: 3,
  chapter2Scene6: 4,
  chapter2Scene7: 4,
  chapter2Scene8: 4,
  chapter2Scene9: 4,
  chapter2Scene10: 4,
  chapter2Scene11: 4,
  chapter2Scene12: 4,
  chapter2Scene13: 4,
  chapter2Scene14: 4,
} as const;

const sceneScrollLengths = {
  chapter2Scene1: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene1),
  chapter2Scene2: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene2),
  chapter2Scene3: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene3),
  chapter2Scene4: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene4),
  chapter2Scene5: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene5),
  chapter2Scene6: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene6),
  chapter2Scene7: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene7),
  chapter2Scene8: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene8),
  chapter2Scene9: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene9),
  chapter2Scene10: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene10),
  chapter2Scene11: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene11),
  chapter2Scene12: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene12),
  chapter2Scene13: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene13),
  chapter2Scene14: scrollLengthFromBeats(sceneBeatCounts.chapter2Scene14),
} as const;

export const multiServiceScenes: SceneConfig[] = [
  {
    id: "chapter-2-scene-1",
    name: "Several Services",
    goal: "Introduce Pico wanting multiple small airport services before boarding.",
    stageId: "opening-world",
    backgroundMode: "white",
    scrollLength: sceneScrollLengths.chapter2Scene1,
    sticky: true,
    asset: "/chapter2/c2-storyboard-1.svg",
    assetAlt: "Pico looking at several small airport services before boarding.",
    copy: {
      eyebrow: "Chapter 2 Scene 1",
      headline: "I want several small services before I board",
      body: "Let me check how they work...",
      caption: "",
    },
  },
  {
    id: "chapter-2-scene-2",
    name: "Repeated Approvals",
    goal: "Show the friction of approving different services and assets repeatedly.",
    stageId: "opening-world",
    backgroundMode: "white",
    scrollLength: sceneScrollLengths.chapter2Scene2,
    sticky: true,
    asset: "/chapter2/c2-storyboard-2-start.svg",
    assetAlt: "Different airport services with different assets requiring repeated approvals.",
    copy: {
      eyebrow: "Chapter 2 Scene 2",
      headline: "Different services. Different assets. I only have CKB.",
      body: "Approve each service? Swap assets too?",
      caption: "",
    },
  },
  {
    id: "chapter-2-scene-3",
    name: "One Connection",
    goal: "Reveal one connection for multiple services and supported assets.",
    stageId: "opening-world",
    backgroundMode: "white",
    scrollLength: sceneScrollLengths.chapter2Scene3,
    sticky: true,
    asset: "/chapter2/c2-storyboard-3.svg",
    assetAlt: "A Fiber connection supporting multiple services and assets.",
      copy: {
        eyebrow: "Chapter 2 Scene 3",
        headline: "Oh... what is this?",
        body: "One pass can connect services and match supported assets?",
        caption: "That sounds great!",
      },
  },
  {
    id: "chapter-2-scene-4",
    name: "Multi-Service Start",
    goal: "Show the multi-service start interaction using the same staggered panel language as Chapter 1.",
    stageId: "transition-world",
    backgroundMode: "white",
    scrollLength: sceneScrollLengths.chapter2Scene4,
    sticky: true,
    asset: "/chapter2/c2-storyboard-4-left-start.svg",
    assetAlt: "Multi-service start flow with phone confirmation.",
    copy: {
      eyebrow: "Chapter 2 Scene 4",
      headline: "",
      body: "",
      caption: "",
    },
  },
  {
    id: "chapter-2-scene-5",
    name: "Airport Pass Channel",
    goal: "Show Fiber opening one channel between Pico and the Fiber Airport Pass for multiple services.",
    stageId: "technical-world",
    backgroundMode: "warm",
    scrollLength: sceneScrollLengths.chapter2Scene5,
    sticky: true,
    asset: "/chapter2/fiber-pass-avatar.png",
    assetAlt: "Fiber Airport Pass payment channel connected to several airport services.",
    copy: {
      eyebrow: "Chapter 2 Scene 5",
      headline: "Behind the scenes, Fiber opens one channel for the pass.",
      body: "The pass uses one Fiber channel to coordinate every supported service.",
      caption: "Pico approves once, then uses what the pass supports.",
    },
  },
  {
    id: "chapter-2-scene-6",
    name: "Try Luggage Storage",
    goal: "Show Pico choosing luggage storage as the first service to try.",
    stageId: "opening-world",
    backgroundMode: "white",
    scrollLength: sceneScrollLengths.chapter2Scene6,
    sticky: true,
    asset: "/chapter2/c2-storyboard-6.svg",
    assetAlt: "Pico deciding to try luggage storage first.",
    copy: {
      eyebrow: "Chapter 2 Scene 6",
      headline: "Let me try the luggage storage first.",
      body: "",
      caption: "",
    },
  },
  {
    id: "chapter-2-scene-7",
    name: "Luggage Storage Payment",
    goal: "Show the luggage storage interaction with start and end states on both panels.",
    stageId: "transition-world",
    backgroundMode: "white",
    scrollLength: sceneScrollLengths.chapter2Scene7,
    sticky: true,
    asset: "/chapter2/c2-storyboard-7-left-start.svg",
    assetAlt: "Luggage storage payment flow with phone and service panel states.",
    copy: {
      eyebrow: "Chapter 2 Scene 7",
      headline: "",
      body: "",
      caption: "",
    },
  },
  {
    id: "chapter-2-scene-8",
    name: "Luggage Storage Route",
    goal: "Show Fiber routing the active payment stream from the airport pass to luggage storage.",
    stageId: "technical-world",
    backgroundMode: "warm",
    scrollLength: sceneScrollLengths.chapter2Scene8,
    sticky: true,
    asset: "/chapter2/luggage-avatar.png",
    assetAlt: "Fiber Airport Pass routing payment to luggage storage.",
    copy: {
      eyebrow: "Chapter 2 Scene 8",
      headline: "Fiber routes the active payment to luggage storage.",
      body: "Pico already connected once. Fiber now routes payment to the luggage storage service.",
      caption: "",
    },
  },
  {
    id: "chapter-2-scene-9",
    name: "Massage Chair Check",
    goal: "Show Pico deciding to double-check the massage chair before using it.",
    stageId: "opening-world",
    backgroundMode: "white",
    scrollLength: sceneScrollLengths.chapter2Scene9,
    sticky: true,
    asset: "/chapter2/c2-storyboard-9.svg",
    assetAlt: "Pico double-checking the massage chair service.",
    copy: {
      eyebrow: "Chapter 2 Scene 9",
      headline: "This takes BTC-sats... but I don't have any.",
      body: "Will it still work with the Fiber Pass?",
      caption: "",
    },
  },
  {
    id: "chapter-2-scene-10",
    name: "Massage Chair Payment",
    goal: "Show the massage chair interaction using the same two-panel start, end, and confirmation pattern.",
    stageId: "transition-world",
    backgroundMode: "white",
    scrollLength: sceneScrollLengths.chapter2Scene10,
    sticky: true,
    asset: "/chapter2/c2-storyboard-10-left-start.svg",
    assetAlt: "Massage chair payment flow with phone and service panel states.",
    copy: {
      eyebrow: "Chapter 2 Scene 10",
      headline: "",
      body: "",
      caption: "",
    },
  },
  {
    id: "chapter-2-scene-11",
    name: "Massage Chair Route",
    goal: "Show Fiber bridging the massage payment into a sats route over Lightning while all services remain active.",
    stageId: "technical-world",
    backgroundMode: "warm",
    scrollLength: sceneScrollLengths.chapter2Scene11,
    sticky: true,
    asset: "/chapter2/massage-avatar.png",
    assetAlt: "Fiber Airport Pass routing a sats payment to the massage chair.",
    copy: {
      eyebrow: "Chapter 2 Scene 11",
      headline: "Fiber Pass bridges Pico’s CKB payment to the massage chair.",
      body: "The massage chair receives sats over Lightning.",
      caption: "",
    },
  },
  {
    id: "chapter-2-scene-12",
    name: "Active Services",
    goal: "Show Pico's active services updating over time until all services are ended or the shared balance reaches the threshold.",
    stageId: "technical-world",
    backgroundMode: "warm",
    scrollLength: sceneScrollLengths.chapter2Scene12,
    sticky: true,
    asset: "/chapter2/fiber-pass-avatar.png",
    assetAlt: "Fiber Airport Pass routing active payments to luggage storage and massage chair.",
    copy: {
      eyebrow: "Chapter 2 Scene 12",
      headline: "Both services are running.",
      body: "Both services keep running while Fiber updates the shared balance in real time.",
      caption: "End the services when Pico is ready.",
    },
  },
  {
    id: "chapter-2-scene-13",
    name: "Close Airport Pass Channel",
    goal: "Show the shared airport pass channel closing and the final Layer 1 settlement distribution.",
    stageId: "technical-world",
    backgroundMode: "warm",
    scrollLength: sceneScrollLengths.chapter2Scene13,
    sticky: true,
    asset: "/chapter2/fiber-pass-avatar.png",
    assetAlt: "Fiber Airport Pass payment channel closing with final settlement.",
    copy: {
      eyebrow: "Chapter 2 Scene 13",
      headline: "Fiber closes the pass channel.",
      body: "The used amount is paid out, and the unused balance returns on Layer 1.",
      caption: "",
    },
  },
  {
    id: "chapter-2-scene-14",
    name: "Airport Pass Summary",
    goal: "Show the final Fiber Airport Pass summary using the real active-services data.",
    stageId: "settlement-world",
    backgroundMode: "white",
    scrollLength: sceneScrollLengths.chapter2Scene14,
    sticky: true,
    asset: "/chapter2/c2-storyboard-14-left-start.svg",
    assetAlt: "Pico tapping the phone after airport services end.",
    copy: {
      eyebrow: "Chapter 2 Scene 14",
      headline: "Fiber Airport Pass summary",
      body: "Pico sees exactly what was paid and returned.",
      caption: "",
    },
  },
];
